spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biblio_database_sqy_m2di?useSSL=false&allowPublicKeyRetrieval=true
    username: User2025ensitech
    password: User2025ensitech
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # ou create-drop si vous voulez recréer la DB à chaque test
    show-sql: true       # pour voir les requêtes SQL pendant les tests
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  test:
    database: replace=none # indique de ne pas remplacer la datasource en test

# Gestion des logs SQL (optionnel, mais utile pour debug)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE